let robotSwapper = new NounSwapper(
    [
        'automaton',
        'cyborg',
        'android',
        'robotics',
        'golem',
        'computer program',
        'general motors',
        'machine',
        'simulator',
        'three laws of', ',robotics',
        'isaac asimov',
        'torpedo',
        'device',
        'industrial robot',
        'josef čapek',
        'karel čapek',
        'humanoid',
        'asimo',
        'simulate',
        'electromechanics',
        'nanorobotics',
        'unimate',
        'hephaestus',
        'computer',
        'swarm robotics',
        'archytas',
        'mozi',
        "rossum's universal robots",
        'czech republic',
        'electromagnet',
        'william grey walter',
        'robot',
        'ios',
        'iphone',
        'ipad',
        'linux',
        'emulator',
        'humanoid',
        'mechanical man',
        'automaton',
        'smartphone',
        'app',
        'gamecube',
        'clone',
        'htc',
        'touchscreen',
        'tablet',
        'pda',
        'console',
        'apple',
        'symbian',
        'software',
        'mobile',
        'samsung',
        'bot',
        'golem',
        'smartphones',
        'macintosh',
        'apps',
        'ipod',
        'os',
        'droid',
        'handheld',
        'desktop',
        'nintendo',
        'ds',
        'browser',
        'playstation',
        'xbox',
        'clones',
        'xp',
        'blackberry',
        'consoles',
        'psp',
        'pc',
        'server'
    ]
)

console.log(robotSwapper.generateNoun())